### ISSUE TITLE
Stonesense causes DF to crash within seconds (specific save)

### ISSUE THREAD

**Issue by mkoponen** [DFHack/stonesense#63] opened 2018-09-24 22:28 UTC
This savegame causes all DF windows to crash within seconds if you pan the view around and never unpause the game when (and only when) Stonesense is on. 

https://drive.google.com/file/d/1c1ffCW3BteOvWGS0WQuXj3Bmcmtcbkaq/view?usp=sharing

How I can reliably reproduce the crash on my system (Windows 10): Using the save game folder from link above, and with unmodified LNP installation with the currently newest version of PyLNP (0.13a), launch DF with only DFHack and stonesense (or launch ssense manually from console, doesn't matter). Use default tileset, and no other plugins enabled. No multilevel, no TWBT, only Stonesense.

Make Stonesense window as large as your display allows. In DF window, with Stonesense following the view, pan up so that you see surface level, pan south so that the brook is at center, and start panning up and down between surface level and above treetops. Do not unpause the game at any point. This shouldn't take more than a few seconds for the game to crash. If you have successfully viewed every Z-level between surface and highest treetop, then the crash is not happening.

When you get to a certain Z-level, all three windows simply close: DF, DFHack console and Stonesense. This does not happen if I don't launch Stonesense but do the same with only DFHack on. Also, if I use a later save from that same fortress, it does not happen, so the profile warning is almost certainly unrelated. The cause must be something that is happening near the river in this save.

There is nothing out of the ordinary in any of the .log files. Stderr.log output from invoking ssense to crash is below.

Invoking: ssense
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: out-of-date sRGB profile with no signature
Client connection established.
Client connection established.
Shutting down client connection.

**Comment by lethosor** [comment] 2023-01-19 03:43
Closing because the save is obsolete. Unsure if this could be a duplicate of https://github.com/DFHack/stonesense/issues/92. Please open a new issue if the problem persists in v50 and is noticeable different from https://github.com/DFHack/stonesense/issues/92.

**Closed by lethosor** 2023-01-19 03:43 UTC
Labels: Crash
