### ISSUE TITLE
Can not issue stone sense commands on mac

### ISSUE THREAD

**Issue by Equilibrium94** [DFHack/stonesense#67] opened 2019-07-01 17:58 UTC
the "c" key is supposed to toggle lowering the walls, but it does nothing. Commands do not work in overlay mode or regular mode. 
I'm  running DFHack version 0.44.05-r2 (release) on x86_64 on a mac

**Comment by lethosor** [comment] 2019-07-01 18:00
Duplicate of #32

**Closed by lethosor** 2019-07-01 18:00 UTC
