### ISSUE TITLE
Doesn't seem to work on Arch Linux 

### ISSUE THREAD

**Issue by sTiKyt** [DFHack/stonesense#70] opened 2020-06-23 09:36 UTC
Dfhack version 0.47.04-r1
OS: Arch Linux
That's what i get in terminal:
```
Sound devices available:
OpenAL Soft
Picking OpenAL Soft. If your desired device was missing, make sure you have the appropriate 32-bit libraries installed. If you wanted a different device, configure ~/.openalrc appropriately.
Initializing OpenAL failed, no sound will be played
Loading bindings from data/init/interface.txt
New window size: 640x300
Font size: 8x12
Resizing grid to 80x25
Resizing font to 8x12

Resetting textures
DFHack is ready. Have a nice day!
DFHack version 0.47.04-r1 (release) on x86_64
Type in '?' or 'help' for general help, 'ls' to see all commands.
Could not load script: onLoad.init-example
Could not load script: onLoad.init-example
Could not load script: onLoad.init-example
Could not load script: onLoad.init-example
Could not load script: onLoad.init-example
Could not load script: onLoad.init-example
[DFHack]# stonesense
Stonesense launched
Using allegro version 5.0.10 r1
[DFHack]# 
```

Also i can't enter any other commands, stonesense window stuck at this forever:

![Screenshot_20200623_123444](https://user-images.githubusercontent.com/35602029/85387873-0ab60900-b54e-11ea-8377-38353a243fff.png)

**Comment by lethosor** [comment] 2020-06-23 12:50
Is there anything that gets logged to stderr.log after starting Stonesense?

**Comment by sTiKyt** [comment] 2020-06-24 04:59
> Is there anything that gets logged to stderr.log after starting Stonesense?

Nope, i don't think so

**Comment by lethosor** [comment] 2020-06-24 14:44
Could you post its contents? Maybe there's some issue that occurs when loading the plugin.

**Comment by sTiKyt** [comment] 2020-06-24 18:10
```
dfhack: hooking successful
DFHack build: 0.47.04-r1-0-g6bdbf5b0
Identifying DF version.
Loading hack/symbols.xml ... OK
v0.47.03 SDL win32 (windows): PE: 0x5E4916E0
v0.47.03 SDL win64 (windows): PE: 0x5E491E82
v0.47.04 SDL win32 (windows): PE: 0x5E5B11F9
v0.47.04 SDL win64 (windows): PE: 0x5E5B1983
v0.47.03 linux32 (linux): MD5: d64e00ffa0be385c2f94a40392d065e6
v0.47.03 linux64 (linux): MD5: 0f184a432dc8b09af70169537e8000b8
v0.47.04 linux32 (linux): MD5: efb418c256e91b42d7fb80da7e6c5073
v0.47.04 linux64 (linux): MD5: edb951bf8b99f162e4078dc007627595
v0.47.03 osx32 (darwin): MD5: 99b655b646e355a115504d89fc5e15a9
v0.47.03 osx64 (darwin): MD5: cd5ef8c61e892f0fec8065353534aee7
v0.47.04 osx32 (darwin): MD5: 1f34439164ee34893f10bde2cd853f7a
v0.47.04 osx64 (darwin): MD5: d838ed45996c72600cd4ca7205ac071a
Loaded 12 DF symbol tables.
Version: v0.47.04 linux64
Initializing Console.
Console is running.
Initializing Plugins.
loading plugin cleaners
loaded plugin cleaners; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin rename
loaded plugin rename; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin dwarfmonitor
loaded plugin dwarfmonitor; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin diggingInvaders
loaded plugin diggingInvaders; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin rendermax
loaded plugin rendermax; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin autotrade
loaded plugin autotrade; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin showmood
loaded plugin showmood; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin RemoteFortressReader
loaded plugin RemoteFortressReader; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin seedwatch
loaded plugin seedwatch; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin plants
loaded plugin plants; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin forceequip
loaded plugin forceequip; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin workflow
loaded plugin workflow; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin changelayer
loaded plugin changelayer; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin stocks
loaded plugin stocks; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin fixveins
loaded plugin fixveins; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin stockpiles
loaded plugin stockpiles; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin stockflow
loaded plugin stockflow; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin resume
loaded plugin resume; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin blueprint
loaded plugin blueprint; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin prospector
loaded plugin prospector; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin strangemood
loaded plugin strangemood; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin autogems
loaded plugin autogems; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin autodump
loaded plugin autodump; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin fastdwarf
loaded plugin fastdwarf; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin map-render
loaded plugin map-render; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin lair
loaded plugin lair; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin title-folder
SDLreal.dll: cannot open shared object file: No such file or directory
SDL.framework/Versions/A/SDL: cannot open shared object file: No such file or directory
SDL.framework/SDL: cannot open shared object file: No such file or directory
loaded plugin title-folder; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin dwarfvet
loaded plugin dwarfvet; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin regrass
loaded plugin regrass; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin generated-creature-renamer
loaded plugin generated-creature-renamer; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin automelt
loaded plugin automelt; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin dig
loaded plugin dig; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin isoworldremote
loaded plugin isoworldremote; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin debug
loaded plugin debug; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin changevein
loaded plugin changevein; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin autohauler
loaded plugin autohauler; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin autoclothing
loaded plugin autoclothing; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin steam-engine
loaded plugin steam-engine; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin confirm
loaded plugin confirm; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin siege-engine
loaded plugin siege-engine; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin burrows
loaded plugin burrows; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin deramp
loaded plugin deramp; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin labormanager
loaded plugin labormanager; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin power-meter
loaded plugin power-meter; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin 3dveins
loaded plugin 3dveins; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin tailor
loaded plugin tailor; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin cleanowned
loaded plugin cleanowned; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin sort
loaded plugin sort; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin ruby
loaded plugin ruby; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin fortplan
loaded plugin fortplan; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin eventful
loaded plugin eventful; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin reveal
loaded plugin reveal; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin jobutils
loaded plugin jobutils; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin add-spatter
loaded plugin add-spatter; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin mode
loaded plugin mode; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin follow
loaded plugin follow; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin building-hacks
loaded plugin building-hacks; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin tweak
loaded plugin tweak; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin petcapRemover
loaded plugin petcapRemover; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin stonesense
loaded plugin stonesense; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin luasocket
loaded plugin luasocket; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin autochop
loaded plugin autochop; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin getplants
loaded plugin getplants; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin autolabor
loaded plugin autolabor; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin fix-armory
loaded plugin fix-armory; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin tiletypes
loaded plugin tiletypes; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin automaterial
loaded plugin automaterial; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin mousequery
loaded plugin mousequery; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin workNow
loaded plugin workNow; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin search
loaded plugin search; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin infiniteSky
loaded plugin infiniteSky; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin tubefill
loaded plugin tubefill; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin pathable
loaded plugin pathable; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin orders
loaded plugin orders; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin buildingplan
loaded plugin buildingplan; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin misery
loaded plugin misery; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin zone
loaded plugin zone; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin filltraffic
loaded plugin filltraffic; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin digFlood
loaded plugin digFlood; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin title-version
loaded plugin title-version; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin embark-tools
loaded plugin embark-tools; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin manipulator
loaded plugin manipulator; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin fix-unit-occupancy
loaded plugin fix-unit-occupancy; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin command-prompt
loaded plugin command-prompt; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin cxxrandom
loaded plugin cxxrandom; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin flows
loaded plugin flows; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin trackstop
loaded plugin trackstop; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin createitem
loaded plugin createitem; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin cleanconst
loaded plugin cleanconst; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin autofarm
loaded plugin autofarm; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin probe
loaded plugin probe; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin nestboxes
loaded plugin nestboxes; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin hotkeys
loaded plugin hotkeys; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin changeitem
loaded plugin changeitem; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin embark-assistant
loaded plugin embark-assistant; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin cursecheck
loaded plugin cursecheck; DFHack build 0.47.04-r1-0-g6bdbf5b0
loading plugin liquids
loaded plugin liquids; DFHack build 0.47.04-r1-0-g6bdbf5b0
Starting the TCP listener.
Starting IO thread.
Starting DF input capture thread.
Listening on port 5000
DFHack is running.
Invoking: multilevel 10
multilevel is not a recognized command.
Invoking: twbt unit_transparency 1
twbt is not a recognized command.
Invoking: twbt workshop_transparency 1
twbt is not a recognized command.
Invoking: twbt redraw_all 0
twbt is not a recognized command.
Invoking: multilevel shadowcolor 0 0 0 0.6
multilevel is not a recognized command.
Invoking: multilevel fogcolor 0.1 0.1 0.17
multilevel is not a recognized command.
Invoking: multilevel fogdensity 0.30 0.25 0.75
multilevel is not a recognized command.
Invoking: startdwarf 7
Invoking: points 1504
no world loaded - cannot modify embark points
Invoking: keybinding add Ctrl-F1 hotkeys
Invoking: keybinding add Alt-F1 hotkeys
Invoking: keybinding add Ctrl-W twaterlvl
Invoking: keybinding add Ctrl-V digv
Invoking: keybinding add Ctrl-Shift-V "digv x"
Invoking: keybinding add Ctrl-C spotclean
Invoking: keybinding add Ctrl-Shift-K autodump-destroy-here
Invoking: keybinding add Alt-Shift-I@dwarfmode/Zones "zone set"
Invoking: keybinding add Ctrl-K autodump-destroy-item
Invoking: keybinding add Ctrl-Alt-S@dwarfmode/Default quicksave
Invoking: keybinding add Ctrl-Shift-N gui/rename
Invoking: keybinding add Ctrl-Shift-T "gui/rename unit-profession"
Invoking: keybinding add Ctrl-Shift-P command-prompt
Invoking: keybinding add Alt-M@dwarfmode/Default "dwarfmonitor prefs"
Invoking: keybinding add Ctrl-F@dwarfmode/Default "dwarfmonitor stats"
Invoking: keybinding add Ctrl-Shift-F@dwarfmode forum-dwarves
Invoking: keybinding add Alt-S@title gui/settings-manager
Invoking: keybinding add Alt-S@dwarfmode/Default gui/settings-manager
Invoking: keybinding add Alt-Q@jobmanagement/Main gui/manager-quantity
Invoking: keybinding add Ctrl-B@dungeonmode adv-bodyswap
Invoking: keybinding add Ctrl-Shift-B@dungeonmode "adv-bodyswap force"
Invoking: keybinding add Shift-O@dungeonmode gui/companion-order
Invoking: keybinding add Ctrl-A@legends "exportlegends all"
Invoking: keybinding add Ctrl-Shift-Z@dwarfmode/Default "stocks show"
Invoking: keybinding add Ctrl-Shift-I@dwarfmode/Default "gui/dfstatus"
Invoking: keybinding add Ctrl-Shift-I@dfhack/lua/dfstatus "gui/dfstatus"
Invoking: keybinding add Alt-P copystock
Invoking: keybinding add Alt-L@dwarfmode/QueryBuilding/Some/Stockpile "gui/stockpiles -load"
Invoking: keybinding add Alt-S@dwarfmode/QueryBuilding/Some/Stockpile "gui/stockpiles -save"
Invoking: keybinding add Ctrl-D job-duplicate
Invoking: keybinding add Shift-A "job-material ALUNITE"
Invoking: keybinding add Shift-M "job-material MICROCLINE"
Invoking: keybinding add Shift-D "job-material DACITE"
Invoking: keybinding add Shift-R "job-material RHYOLITE"
Invoking: keybinding add Shift-I "job-material CINNABAR"
Invoking: keybinding add Shift-B "job-material COBALTITE"
Invoking: keybinding add Shift-O "job-material OBSIDIAN"
Invoking: keybinding add Shift-T "job-material ORTHOCLASE"
Invoking: keybinding add Shift-G "job-material GLASS_GREEN"
Invoking: keybinding add Alt-Shift-N "sort-units name" "sort-items description"
Invoking: keybinding add Alt-Shift-R "sort-units arrival"
Invoking: keybinding add Alt-Shift-T "sort-units profession" "sort-items type material"
Invoking: keybinding add Alt-Shift-Q "sort-units squad_position" "sort-items quality"
Invoking: keybinding add Ctrl-M@dwarfmode/QueryBuilding/Some gui/mechanisms
Invoking: keybinding add Alt-R@dwarfmode/QueryBuilding/Some gui/room-list
Invoking: keybinding add Alt-L@dwarfmode/LookAround gui/liquids
Invoking: keybinding add Ctrl-Shift-M@dwarfmode/Build/Position/Trap gui/power-meter
Invoking: keybinding add Alt-A@dwarfmode/QueryBuilding/Some/SiegeEngine gui/siege-engine
Invoking: keybinding add Ctrl-W@layer_military/Equip/Customize/View gui/choose-weapons
Invoking: keybinding add Ctrl-C@layer_military/Uniforms gui/clone-uniform
Invoking: keybinding add Alt-P@dwarfmode/Hauling/DefineStop/Cond/Guide gui/guide-path
Invoking: keybinding add Alt-A@dwarfmode/QueryBuilding/Some/Workshop/Job gui/workshop-job
Invoking: keybinding add Alt-W@dwarfmode/QueryBuilding/Some/Workshop/Job gui/workflow
Invoking: keybinding add Alt-W@overallstatus "gui/workflow status"
Invoking: keybinding add Alt-W@dfhack/lua/status_overlay "gui/workflow status"
Invoking: keybinding add Shift-B@pet/List/Unit "gui/autobutcher"
Invoking: keybinding add P@dwarfmode/QueryBuilding/Some/Weaponrack gui/assign-rack
Invoking: keybinding add Alt-Shift-P@dwarfmode/LookAround gui/pathable
Invoking: tweak stable-cursor
Enabled tweak stable-cursor (stable_cursor_hook::feed)
Invoking: tweak advmode-contained
Enabled tweak advmode-contained (advmode_contained_hook::feed)
Invoking: tweak fast-trade
Enabled tweak fast-trade (fast_trade_assign_hook::feed)
Enabled tweak fast-trade (fast_trade_select_hook::feed)
Invoking: tweak military-stable-assign
Enabled tweak military-stable-assign (military_assign_hook::feed)
Invoking: tweak military-color-assigned
Enabled tweak military-color-assigned (military_assign_hook::render)
Invoking: tweak craft-age-wear
Enabled tweak craft-age-wear (craft_age_wear_hook::ageItem)
Invoking: tweak farm-plot-select
Enabled tweak farm-plot-select (farm_select_hook::feed)
Enabled tweak farm-plot-select (farm_select_hook::render)
Invoking: tweak import-priority-category
Enabled tweak import-priority-category (takerequest_hook::feed)
Enabled tweak import-priority-category (takerequest_hook::render)
Invoking: tweak condition-material
Enabled tweak condition-material (condition_material_hook::feed)
Invoking: tweak hotkey-clear
Enabled tweak hotkey-clear (hotkey_clear_hook::feed)
Enabled tweak hotkey-clear (hotkey_clear_hook::render)
Invoking: tweak embark-profile-name
Enabled tweak embark-profile-name (embark_profile_name_hook::feed)
Invoking: tweak block-labors              # Prevents labors that can't be used from being toggled
Enabled tweak block-labors (block_labors_hook::feed)
Enabled tweak block-labors (block_labors_hook::render)
Invoking: tweak burrow-name-cancel
Enabled tweak burrow-name-cancel (burrow_name_cancel_hook::feed)
Invoking: tweak cage-butcher
Enabled tweak cage-butcher (cage_butcher_hook::feed)
Enabled tweak cage-butcher (cage_butcher_hook::render)
Invoking: tweak civ-view-agreement
Enabled tweak civ-view-agreement (civ_agreement_view_hook::render)
Invoking: tweak eggs-fertile
Enabled tweak eggs-fertile (egg_fertile_hook::render)
Invoking: tweak fps-min
Enabled tweak fps-min (fps_min_hook)
Invoking: tweak hide-priority
Enabled tweak hide-priority (hide_priority_hook::feed)
Enabled tweak hide-priority (hide_priority_hook::render)
Invoking: tweak max-wheelbarrow
Enabled tweak max-wheelbarrow (max_wheelbarrow_hook::render)
Enabled tweak max-wheelbarrow (max_wheelbarrow_hook::feed)
Invoking: tweak shift-8-scroll
Enabled tweak shift-8-scroll (shift_8_scroll_hook::feed)
Invoking: tweak title-start-rename
Enabled tweak title-start-rename (title_start_rename_hook::feed)
Enabled tweak title-start-rename (title_start_rename_hook::render)
Invoking: tweak tradereq-pet-gender
Enabled tweak tradereq-pet-gender (pet_gender_hook::render)
Invoking: enable title-version
Invoking: enable manipulator
Invoking: enable search
Invoking: enable automaterial
Invoking: enable  confirm  dwarfmonitor  mousequery  autogems  automelt  autotrade  buildingplan  resume  trackstop  zone  stocks  autochop  stockpiles
Invoking: embark-tools enable sticky sand mouse
Invoking: modtools/extra-gamelog enable
Invoking: enable gui/extended-status
Invoking: view-item-info enable
Invoking: gui/load-screen enable
Invoking: sc-script add SC_WORLD_LOADED onLoad.init-example
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Console is shutting down properly.
```

**Comment by lethosor** [comment] 2020-06-24 18:23
Looks like the plugin loaded fine. The libpng warnings might be related - in the case of #63, they apparently came up after starting Stonesense. Do you happen to know what version of libpng you have (or if it's installed)? If you're able to upgrade or downgrade, that might be worth trying. I think libpng incompatibilities have caused similar issues before, but I'm not entirely familiar with them, so I'm sorry I'm not able to be more helpful with this.

**Comment by sTiKyt** [comment] 2020-06-25 03:49
@lethosor i have libpng-1.6.37-2

**Comment by lc-thomas** [comment] 2020-07-16 12:24
This issue is discussed there : https://github.com/DFHack/stonesense/issues/68

**Comment by lethosor** [comment] 2020-07-16 17:20
That's a different issue (or at least the symptoms are different) - this is a hang, while #68 is a crash. @sTiKyt, you could try upgrading Stonesense to see if that helps, though. Instructions: https://github.com/DFHack/stonesense/issues/68#issuecomment-651423498

**Comment by RussellPaine** [comment] 2020-07-24 20:54
I am also having the same issue on Arch Linux. Same version, same OS. My stderr.log looks the same without the libpng errors/warnings.
[stderr.log](https://github.com/DFHack/stonesense/files/4974192/stderr.log)

**Comment by lethosor** [comment] 2020-07-24 21:09
Does upgrading stonesense help? https://github.com/DFHack/stonesense/issues/68#issuecomment-651423498
(The fixes since 0.47.04-r1 haven't specifically targeted this issue, but there's a chance that they helped)

**Comment by RussellPaine** [comment] 2020-07-26 00:22
I followed the instructions and it does indeed fix the issue. Thanks for the help.

**Comment by lethosor** [comment] 2020-07-26 01:27
Cool! Maybe https://github.com/DFHack/stonesense/commit/b4ff44f788a37e6adb43372eb8b29b310ff95101 fixed it, then (that's another change since 0.47.04-r1). I'm interested in hearing whether that fixes it for others, though (@sTiKyt?).

**Comment by G0BL1N** [comment] 2020-08-05 15:32
@lethosor If you need other confirmations, I had the same exact problem on Arch Linux, and updating Stonesense, did resolve it. Don't know which commit fixes it, but latest version as of today works perfectly on Arch.

**Comment by lethosor** [comment] 2020-08-05 16:04
Cool, thanks. My best guess is that it's the commit I linked, since it deals with Allegro on a fairly low level, and could help with distro-specific behavior caused by different Allegro versions/builds. I'll close this, but @sTiKyt, feel free to reopen if your issue persists after upgrading, particularly since we haven't identified the exact issue.

**Closed by lethosor** 2020-08-05 16:04 UTC
